name: DeployEcommerce

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            owilsonjunior/fake-shop:latest
            owilsonjunior/fake-shop:${{ github.run_number }}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autentication AWS
        run: echo "Executando o comando aws configure"
      - name: Kubectl configuration
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy application in Kubernets
        run: echo "Executando o comando kubectl apply"
